# Generated by Django 4.0.5 on 2022-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='new_message',
            field=models.BooleanField(default=False, verbose_name='Есть новые сообщения'),
        ),
    ]
