# Generated by Django 4.0.5 on 2022-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1000, verbose_name='Сообщение'),
        ),
    ]
